gen_embed_header:
	python gen_embed_header.py > embed.h
	mv embed.h ../src/

download_deps:
	wget https://cdn.jsdelivr.net/npm/htmx.org@2.0.8/dist/htmx.min.js -O htmx.js
	wget https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.fluid.classless.red.min.css -O pico.css
